import type { Metadata } from "next";
import { Inter, Kanit } from "next/font/google";
import "./globals.css";
import Providers from "@/lib/providers/Providers";
import Navbar from "@/components/shared/Navbar";

const inter = Inter({ subsets: ["latin"] });
export const kanit = Kanit({ weight: "400", subsets: ["latin"], variable: "--font-kanit" });

export const metadata: Metadata = {
  title: "IdeaFizz",
  description: "Social media content generated by AI",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
